FROM ghcr.io/muniftanjim/stremthru

ENV STREMTHRU_HTTP_PROXY=
ENV STREMTHRU_TUNNEL=
ENV STREMTHRU_PROXY_AUTH=
ENV STREMTHRU_STORE_AUTH=
ENV STREMTHRU_PEER_URI=
ENV STREMTHRU_REDIS_URI=
ENV STREMTHRU_DATABASE_URI=sqlite://./data/stremthru.db
