FROM ghcr.io/muniftanjim/stremthru

ENV STREMTHRU_HTTP_PROXY=
ENV STREMTHRU_TUNNEL=
ENV STREMTHRU_PROXY_AUTH=
ENV STREMTHRU_STORE_AUTH=
ENV STREMTHRU_PEER_URI=
ENV STREMTHRU_REDIS_URI=
ENV STREMTHRU_DATABASE_URI=postgres://postgres:dFPKyy979gBT1J4H@db.qfkswkzwnkbkrilwsmbu.supabase.co:5432/postgres
