FROM ghcr.io/muniftanjim/stremthru:latest

ENV STREMTHRU_HTTP_PROXY=true
ENV STREMTHRU_TUNNEL=true
ENV STREMTHRU_PROXY_AUTH=vini:0524988
ENV STREMTHRU_STORE_AUTH=
ENV STREMTHRU_PEER_URI=
ENV STREMTHRU_REDIS_URI=
ENV STREMTHRU_DATABASE_URI=sqlite://./data/stremthru.db
